# Generated by Django 2.2.6 on 2019-11-21 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(max_length=30)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('gtin', models.CharField(blank=True, max_length=14)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('condicao', models.CharField(choices=[('NE', 'Não Especificado'), ('NO', 'Novo'), ('US', 'Usado')], default='NO', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
