# Generated by Django 2.2.6 on 2019-11-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
    ]
