# Generated by Django 2.2.6 on 2019-11-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191121_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='condicao',
            field=models.CharField(choices=[('NE', 'Não Especificado'), ('NO', 'Novo'), ('US', 'Usado')], default='NO', max_length=2, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código GTIN'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Situação'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('codigo', 'user'), name='codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('gtin', 'user'), name='gtin_unico'),
        ),
    ]
