# Generated by Django 2.2.7 on 2019-11-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191121_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='E', max_length=1, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Produto')),
            ],
        ),
    ]
