# Generated by Django 2.2.7 on 2019-11-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.Produto'),
        ),
    ]
