# Generated by Django 2.2.7 on 2019-11-25 00:53

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191124_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=datetime(2019, 11, 24, 21, 00, 00), verbose_name='Data do cadastro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Produto'),
        ),
    ]
