# Generated by Django 2.2.7 on 2019-11-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191124_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='total_estoque',
            field=models.IntegerField(default=0, editable=False, verbose_name='Estoque'),
        ),
    ]
