# Generated by Django 2.2.7 on 2019-11-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_produto_total_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código GTIN'),
        ),
    ]
