# Generated by Django 3.0.3 on 2020-02-17 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200216_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do cadastro'),
            preserve_default=False,
        ),
    ]
