# Generated by Django 3.0.3 on 2020-02-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_loja'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produto',
            name='codigo_unico',
        ),
        migrations.RemoveConstraint(
            model_name='produto',
            name='gtin_unico',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='user',
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Loja'),
            preserve_default=False,
        ),
    ]
