# Generated by Django 3.0.3 on 2020-02-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200222_1243'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loja',
            constraint=models.UniqueConstraint(fields=('loja_principal', 'user'), name='loja_principal_unica'),
        ),
    ]
